name: ci

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 0 * * *' # Everyday at ~00:00 UTC

jobs:
  prep:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.now.outputs.formattedTime }}
      head: ${{ steps.commit.outputs.hash }}

    steps:
      - name: Get Date # To use as tag
        uses: 1466587594/get-current-time@v1
        id: now
        with:
          format: YYYY.MM.DD

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get commit hash # To keep every build on same commit
        id: commit
        run: echo "::set-output name=hash::$(curl -fsSL https://dl.deno.land/canary-latest.txt)"

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.5.2

      - name: Generate Release Notes
        run: deno run -A ./.github/notes.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.now.outputs.formattedTime }}
          HEAD_COMMIT: ${{ steps.commit.outputs.hash }}

      - name: Upload release notes
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: notes
          path: notes.md

  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: prep

    steps:
      - name: Fetch builds
        run: |
          wget https://dl.deno.land/canary/${{ needs.prep.outputs.head }}/deno-x86_64-apple-darwin.zip
          wget https://dl.deno.land/canary/${{ needs.prep.outputs.head }}/deno-x86_64-unknown-linux-gnu.zip
          wget https://dl.deno.land/canary/${{ needs.prep.outputs.head }}/deno-x86_64-pc-windows-msvc.zip

      - name: Extract deno
        run: unzip deno-x86_64-unknown-linux-gnu.zip

      - name: Export Type Docs
        run: ./deno types > lib.deno.d.ts

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            deno-x86_64-unknown-linux-gnu.zip
            deno-x86_64-apple-darwin.zip
            deno-x86_64-pc-windows-msvc.zip
            lib.deno.d.ts

  release:
    needs: [prep, fetch]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ needs.prep.outputs.tag }}'
          name: '${{ needs.prep.outputs.tag }}'
          artifacts: 'release/*'
          bodyFile: 'notes/notes.md'
          token: ${{ secrets.GITHUB_TOKEN }}
